server:
  port: 8089
spring:
  profiles:
    active: dev
  application:
    name: spring-cloud-config-client
  config:
    import: optional:configserver:http://localhost:8088
  cloud:
    config:
      name: fund-config
      profile: sandbox
management:
  endpoints:
    web:
      exposure:
        include: refresh
